### ISSUE TITLE
GenEd News

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#107]
I'm confused about how to handle new press releases:
- I created posts for the last two press releases, but I don't know how to get them to show up on the GenEd news main page, http://teachgen.hayg.info/gened-news/
- I don't know how to get the headline to show up on the individual press release page: http://teachgen.hayg.info/gened-ncss-celebrate-social-responsibility
- I screwed something up, so that the full press release shows up on the GenEd News page.
- If you let me know how to work within the admin for press releases, I can ask Seda to add the old press releases to GenEd News

- On the homepage, when I click on the press release, it jumps to the photo, not to the individual press release page.

- I hope we can modify the style that shows up in the homepage press release box, but not effect the press release page style? I think the headlines in the homepage news box should be bigger, stand out more. I'm not sure how to access the text of that box.

**Comment by copacetic** [comment]
1. I see them. Could you clarify on this one?
2. Nice catch. This is a bug. I'll fix it.
3. I addressed this in another issue. You need to add a 'Read more' button where you want the post to cut off. Otherwise, we don't know where the summary should end.
4. Sounds like a great idea.
5. That's because you need to add the 'Read more'. If you don't, the post will be too big and the user won't have a way to see all of it. Currently, the only clickable thing is the image, which means that's what you click. It just shows you the image alone, though.
6. The text of the box is the text of the press release, but you control how much of it is shown by adding a 'Read more'

**Comment by copacetic** [comment]
http://teachgen.hayg.info/gened-news/

For #2: Titles, dates, and author should show up when you click on a PR now.

**Comment by Hasmig** [comment]
OK, I understand about the "read more" button.

I'm glad we can now see the titles, dates in the PR. But, I don't think I want to see, "Posted on November 19, 2015 by Roxanne Makasdjian" at the top of each PR page. I don't want people to see when it was posted and who posted it.

I wish we could make the headlines bold font. I don't think they stand out enough.

**Comment by copacetic** [comment]
Ok, I fixed the "Posted on..." thing. It shouldn't be there anymore.

I noticed what you mention about the "They Shall Not Perish"... I'm not sure how to fix it :/

The headlines should also be bolded now.

You should be able to do whatever you can through the WordPress editor. If you want to change styles site-wide, I can help with that.

Does every press release typically have an image associated with it? If so, adding images should be fairly straightforward :)

**Comment by Hasmig** [comment]
That's weird... I can't find the font size and style functions in the Wordpress editor.
How did you bold the headlines? Can I do that myself? Can we do it for the headlines on the main GenEd News page?
Yes, our press releases will always have images with them.

**Comment by copacetic** [comment]
Fixed, you can now set font size and style.
