### ISSUE TITLE
Posters display

### ISSUE THREAD

**Issue by Hasmig** [GenEdProject/TeachGenocideSite#64]
I'd like to figure out a way to display closeups of the posters and/or include the full text of the posters.

**Comment by SourenP** [comment]
http://teachgen.hayg.info/resources/posters/
http://teachgen.hayg.info/poster-1/

**Comment by Hasmig** [comment]
Melani designed a page for the posters page with the posters lined up at the bottom. Did you see that?

I do like how you've been able to put one whole poster on the page on the "poster-1" page.

**Comment by SourenP** [comment]
I was a bit confused by that design because it's not clear which poster title matches which image.

I can either change what I made now by adding that brown background to each poster but keep them in rows. (4 boxes, each with text on the left image on the right)

Or I could make it exactly how the design is.

Let me know.

**Comment by Hasmig** [comment]
I think it would be good to see all the posters lined up with their titles, maybe just under the top description. Then maybe display each separately, as you have, with their descriptions, and with hyperlinks to the blown-up versions.

**Comment by SourenP** [comment]
Only the first poster is fully functional, but if this design works, I'll go ahead and add the rest.
http://teachgen.hayg.info/resources/posters/

Note that the highlighting will be improved for the blow up (http://teachgen.hayg.info/poster-1/).

Also, do you guys have pdfs of the posters? Or one large full piece image we could provide?

**Comment by Hasmig** [comment]
I don't know if we had pdfs, but we lost most of our archives recently when Raffi's home was burglarized, so I'm pretty sure we don't have them. I'll ask.

I actually hadn't realized the highlighting until you mentioned it now. I thought I was just looking at a large version of the full poster, and I was actually surprised that it was big enough to be readable. I'm not sure if we should do that, with the close-up sections of the posters. Would it be possible to enable some kind of zooming function, instead?  If not, I'm wondering whether we should transcribe the whole poster and post the text....?

**Comment by SourenP** [comment]
I think the point of that feature in the old site (http://www.teachgenocide.com/posters/poster1.htm) was to be able to print out the posters by section and then stitch the pieces back together (since you can only print out small pages).

Do we still want users to be able to download pictures of the different part of the posters?
Or should we transcribe the posters and have the users make their own posters using the text provided?

**Comment by Hasmig** [comment]
Hi Souren,

Sorry, I forgot my login info, so I can't get into GitHub today from work.

We want teachers to be able to read what's on the posters, but not print them out, because they can order the real-size posters from us.
 
Sincerely,
Roxanne Makasdjian


________________________________

**Comment by SourenP** [comment]
Replying to the email just makes a comment, so this works!

Ok, to finalize, how do we want it? 
I assume this design looks good as is (I'll add the posters soon): http://teachgen.hayg.info/resources/posters/

But when you view an individual poster, since we don't have a large images of them,  I'm not sure how we want them to view the text.
What we currently have is small snippets of each poster.
If Melani stitch those together and make one big image file for each poster, we could have each poster expand to that large image on a new page. (just like how the first poster can be enlarged now, but without the highlighting)

**Comment by SourenP** [comment]
@Hasmig

**Comment by SourenP** [comment]
I think the page is done.

**Comment by Hasmig** [comment]
That's great. Is there a reason why the five posters across the top hyperlink to a small version of each poster. I'm not sure how useful that is. Let's go ahead and link those to the large poster PDFs. Also, can we fit a larger size poster next to each individual description?

**Comment by copacetic** [comment]
@Hasmig it should be fixed now

**Comment by Hasmig** [comment]
Thanks, Hayg,
So what do you think of making the size of the poster images on the right side of the page larger?

**Comment by SourenP** [comment]
Big enough to be readable, or something like 1.5 times the size?

**Comment by SourenP** [comment]
Big enough to be readable, or something like 1.5 times the size?

**Comment by copacetic** [comment]
I think @SourenP has the right question for this. If the posters are too big it'll make the page really long and require a lot of scrolling--a problem we already have on the site.

**Comment by Hasmig** [comment]
Hi Guys - No, I'm not envisioning a big difference, just so it fills that space a little more. Maybe it needs to be set higher, flush with the title of the poster on the left.

**Comment by SourenP** [comment]
Made the template display larger images.

**Comment by Hasmig** [comment]
Thanks.
